language: objective-c
osx_image: xcode8.2

env:
    global:
        - PROJECT=GLTableCollectionView.xcodeproj
        - SCHEME=GLTableCollectionView
        - SDK=iphonesimulator10.2
        - DESTINATION="platform=iOS Simulator,OS=latest,name=iPhone 5"

before_install:
    - brew update
    - brew upgrade
    - gem update
    - gem install xcpretty
    - gem install xcpretty-travis-formatter
    - gem clean
    - xcodebuild -version
    - xcodebuild -showsdks

    # This command will fix Travis CI duplicated simulators build issue
    # happening while using Xcode 8.2 + iOS simulator 10.2 configuration. Be
    # sure to check GitHub issue #7031
    # (https://github.com/travis-ci/travis-ci/issues/7031) for updates and, as
    # soon as the Travis team fix the issue, remove this line.
    - xcrun simctl delete D0257C83-DB81-4567-93EC-4C6DF23DC24C

script: xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug test | xcpretty -f `xcpretty-travis-formatter` && exit ${PIPESTATUS[0]}
