language: objective-c
osx_image: xcode8.2

env:
    global:
        - PROJECT=GLTableCollectionView.xcodeproj
        - SCHEME=GLTableCollectionView
        - SDK=iphonesimulator10.2
        - DESTINATION="platform=iOS Simulator,OS=latest,name=iPhone 5"

before_install:
    - brew update
    - brew upgrade
    - gem update
    - gem install xcpretty
    - gem install xcpretty-travis-formatter
    - gem clean
    - xcodebuild -version
    - xcodebuild -showsdks
    - xcrun simctl delete DB794781-65A7-4884-8D00-AAC3CBD39A44

script: xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug test | xcpretty -f `xcpretty-travis-formatter` && exit ${PIPESTATUS[0]}
