language: objective-c
osx_image: xcode8.1

env:
    global:
        - PROJECT = GLTableCollectionView.xcodeproj
        - SCHEME = GLTableCollectionView
        - SDK = iphonesimulator10.1
        - DESTINATION = "name=iPhone 5,OS=10.1"

xcode_project: GLTableCollectionView.xcodeproj
xcode_scheme: GLTableCollectionView
before_install:
    - xcodebuild -version
    - xcodebuild -showsdks

script: xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug test
