language: objective-c
osx_image: xcode8.1

env:
    global:
        - PROJECT=GLTableCollectionView.xcodeproj
        - SCHEME=GLTableCollectionView
        - SDK=iphonesimulator10.1
        - DESTINATION="OS=10.1,name=iPhone 5"

xcode_project: GLTableCollectionView.xcodeproj
xcode_scheme: GLTableCollectionView
before_install:
    - brew update
    - brew upgrade
    - gem update
    - gem install xcpretty
    - xcodebuild -version
    - xcodebuild -showsdks

script: xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug test | xcpretty && exit ${PIPESTATUS[0]}
